### ISSUE TITLE
removeItem

### ISSUE THREAD

**Issue by xeux** [mig-hub/cart-js#1]
I have found this useful to me.

If anyone want to know how to remove an item from the cart:

`
function removeItem(item_id) {
	var item_index = Cart.indexOfItem(item_id);
	Cart.items.splice(item_index);
	Cart.save();
	// update template
}
`

**Comment by mig-hub** [comment]
Hello @xeux , thank you for your message. It is actually a very good point. I've been too much of a minimalist on this one. The way I use it is that generally the quantity is 1 or a little bit more so I just do `addItem` with "-1" until it is removed.

I will definitely add this functionality to remove an item completely, regardless of the quantity. I'll post a message back here when this is done.

Thank you.
mig
